### ISSUE TITLE
Playground cannot query alias environment

### ISSUE THREAD

**Issue by whitep4nth3r** [contentful/contentful-graphql-playground-app#2]
On load of the playground, I have observed the following behaviour:

- I have an alias environment which is pointed to 'master'
- Regardless of whether I have set the Contentful web app to point to 'production' or 'master', the environment that the playgrounds points to is 'production' by default
- Queries fail with http 400 on 'production' in the playground
- Queries succeed on 'master' regardless of the web app environment selected

**Comment by stefanjudis** [comment]
@whitep4nth3r this should be fixed now. :) Thanks for reporting. 

Let me know if you run into more issues. :)
